[shooter]
turretPosition.p = 0.05
turretPosition.i = 0.0
turretPosition.d = 0.0

turretVelocity.p = 0.5
turretVelocity.i = 0.0
turretVelocity.d = 0.1
turretVelocity.f = 0.85

shooterVelocity.p = 0.0007
shooterVelocity.i = 0.0
shooterVelocity.d = 0.01
shooterVelocity.f = 0.0002

shootingSpeed.near = 4400
shootingSpeed.far  = 4100

[intake]
speed.load  = 0.725
speed.shoot = 0.75

[controlPanel]
extraDegrees = 90.0 # degrees to rotate past 3 rotations
p = 0.1

[drivetrain]
kinematics.ks = 0.135
kinematics.kv = 2.82
kinematics.ka = 0.73
kinematics.kw = 0.9167
