name: WPILib CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install toolchain
      run: sh ./gradlew installRoboRioToolchain
    - name: build
      run: sh ./gradlew build